// executas/tokenbrief/src/clients/config.ts — ch06 §6.10 knobs; "added" = not in §6.10
// (Chapter 10: four §6.5 thresholds had no knob, so no rule contains a literal).
const n = (key: string, dflt: number): number => {
  const raw = process.env[key];
  const v = raw === undefined || raw === "" ? NaN : Number(raw);
  return Number.isFinite(v) ? v : dflt;
};

export const CONFIG = Object.freeze({
  CG_BASE: "https://api.coingecko.com/api/v3",
  DS_BASE: "https://api.dexscreener.com",
  COINGECKO_API_KEY: process.env.COINGECKO_API_KEY || undefined, // local runs only
  RESOLVE_MAX_CANDIDATES: n("RESOLVE_MAX_CANDIDATES", 5),
  RESOLVE_DOMINANCE_RATIO: n("RESOLVE_DOMINANCE_RATIO", 20),
  PAIRS_TOP_N: n("PAIRS_TOP_N", 5),
  PAIR_MIN_LIQ_USD: n("PAIR_MIN_LIQ_USD", 1000),
  RISK_FRESH_HIGH_DAYS: n("RISK_FRESH_HIGH_DAYS", 7),
  RISK_FRESH_WARN_DAYS: n("RISK_FRESH_WARN_DAYS", 30),
  RISK_LIQ_HIGH_USD: n("RISK_LIQ_HIGH_USD", 50_000),
  RISK_LIQ_WARN_USD: n("RISK_LIQ_WARN_USD", 250_000),
  RISK_THIN_RATIO: n("RISK_THIN_RATIO", 0.01),
  RISK_THIN_MIN_CAP_USD: n("RISK_THIN_MIN_CAP_USD", 1_000_000), // added
  RISK_TWIN_MIN_CAP_USD: n("RISK_TWIN_MIN_CAP_USD", 1_000_000),
  RISK_TWIN_MAX_RANK: n("RISK_TWIN_MAX_RANK", 2000),
  RISK_FDV_WARN: n("RISK_FDV_WARN", 3),
  RISK_FDV_HIGH: n("RISK_FDV_HIGH", 10),
  RISK_PAIR_CONC_RATIO: n("RISK_PAIR_CONC_RATIO", 0.9), // added
  RISK_SPIKE_WARN_PCT: n("RISK_SPIKE_WARN_PCT", 50),
  RISK_SPIKE_HIGH_PCT: n("RISK_SPIKE_HIGH_PCT", 150),
  RISK_VOL_LIQ_RATIO: n("RISK_VOL_LIQ_RATIO", 20),
  RISK_VOL_MIN_USD: n("RISK_VOL_MIN_USD", 10_000), // added
  RISK_VOL_DEAD_CAP_USD: n("RISK_VOL_DEAD_CAP_USD", 10_000_000), // added
  RISK_NO_SELLS_MIN_BUYS: n("RISK_NO_SELLS_MIN_BUYS", 20),
  RISK_SELL_PRESSURE_RATIO: n("RISK_SELL_PRESSURE_RATIO", 0.7),
  RISK_SELL_PRESSURE_MIN_TXNS: n("RISK_SELL_PRESSURE_MIN_TXNS", 50),
  HTTP_TIMEOUT_MS: n("HTTP_TIMEOUT_MS", 8000),
  HTTP_RETRIES: n("HTTP_RETRIES", 2),
  CG_MIN_INTERVAL_MS: n("CG_MIN_INTERVAL_MS", 2100),
  DS_MIN_INTERVAL_MS: n("DS_MIN_INTERVAL_MS", 250),
  LIMITER_MAX_WAIT_MS: n("LIMITER_MAX_WAIT_MS", 20_000),
  CACHE_SEARCH_TTL_S: n("CACHE_SEARCH_TTL_S", 600),
  CACHE_MARKETS_TTL_S: n("CACHE_MARKETS_TTL_S", 300),
  CACHE_COIN_TTL_S: n("CACHE_COIN_TTL_S", 90),
  CACHE_CONTRACT_TTL_S: n("CACHE_CONTRACT_TTL_S", 600),
  CACHE_PAIRS_TTL_S: n("CACHE_PAIRS_TTL_S", 60),
  CACHE_PAIR_TTL_S: n("CACHE_PAIR_TTL_S", 600),
  CACHE_NEGATIVE_TTL_S: n("CACHE_NEGATIVE_TTL_S", 300),
  CACHE_RESOLVED_TTL_S: n("CACHE_RESOLVED_TTL_S", 600),
  CACHE_STALE_S: n("CACHE_STALE_S", 900),
  CACHE_MAX_ENTRIES: n("CACHE_MAX_ENTRIES", 500),
});

export type Config = typeof CONFIG;
